export type PolicySection = { title: string; paragraphs: string[]; bullets?: string[] };
export const policies: Record<string, { title: string; description: string; sections: PolicySection[] }> = {
  terms: {
    title: 'Terms of use', description: 'The terms for using the ProfitPilot website and trading workspace.', sections: [
      { title: '1. The service', paragraphs: ['ProfitPilot is software for connecting a supported exchange account, viewing trading activity, and using account controls. Your exchange account, exchange relationship, and funds remain separate from this website. “ProfitPilot” refers to the service offered under this brand. Service and operator inquiries can be sent to support@profitpilot.in.'] },
      { title: '2. Your account and eligibility', paragraphs: ['Use the service only if you are at least 18, have legal capacity to enter into an agreement, and are permitted to use the connected exchange and relevant products in your location. Provide accurate account information and protect your sign-in credentials. You are responsible for activity you authorize through your account. Do not share access or connect an account you do not have authority to manage.'] },
      { title: '3. Exchange authorization and controls', paragraphs: ['Connecting an exchange API key authorizes the permissions granted to that key. Review those permissions carefully and use a trade-only key without withdrawal access. API keys can be revoked at the exchange. Pausing new entries does not itself close existing positions. A submitted close request is not a guarantee of a fill or a particular execution price. Confirm final account and order status at the exchange.'] },
      { title: '4. Trading risk and information', paragraphs: ['Trading decisions and connected-account activity involve risk. Software, charts, account indicators, and website content are not personalized investment, tax, or legal advice. Automation cannot guarantee profit or prevent losses. Read the separate Risk Disclosure before connecting an account or enabling trading. Illustrative product previews are not actual performance results.'] },
      { title: '5. Fees and billing', paragraphs: ['The displayed performance-fee model charges 30% of eligible net new realized profit after applicable carried-forward losses. Refer to Pricing and your actual monthly invoice for the amount assessed. Exchange charges and taxes are separate from the service fee unless expressly stated. INR displays use Delta Exchange India’s fixed rate of ₹85 per USD; it does not alter the underlying USD record or invoice. Billing disputes and account cancellation are covered on the Billing & Refunds page.'] },
      { title: '6. Acceptable use', paragraphs: ['Do not use the service unlawfully, attempt to access another customer’s records, bypass access controls, interfere with the service, or misuse third-party systems. Do not reproduce proprietary software or branding without permission, except as allowed by applicable law.'] },
      { title: '7. Availability and account closure', paragraphs: ['Access depends on the website, authentication provider, network, and exchange. Outages and delayed data can occur. Access may be restricted for security, misuse, nonpayment, or legal reasons. You can request account closure through support. Closing website access or revoking a key does not automatically liquidate positions or settle amounts owed at the exchange.'] },
      { title: '8. Responsibility and applicable law', paragraphs: ['Each party remains responsible for its obligations under applicable law. Nothing in these terms excludes liability or consumer rights that cannot lawfully be excluded. These terms are governed by applicable laws of India; disputes are subject to courts with lawful jurisdiction. Contact support first so that account or billing issues can be investigated. Material changes will be reflected in the updated policy date and communicated where required.'] },
    ],
  },
  privacy: {
    title: 'Privacy policy', description: 'What the service processes, why it is needed, and how to contact us about your data.', sections: [
      { title: '1. Information used by the service', paragraphs: ['Depending on the features you use, ProfitPilot processes account and sign-in details, name, email address, phone number, connected-exchange API credentials, account settings, balance and position information, trade activity, billing records, and support correspondence. Hosting and authentication services may also process technical information such as IP addresses, browser details, timestamps, and security logs.'] },
      { title: '2. Why this information is processed', paragraphs: ['Information is used to authenticate users, connect authorized exchange accounts, display the workspace, operate requested features, calculate and show billing records, respond to support requests, investigate errors, and protect access to the service. Do not submit an API secret or password in an ordinary support message. Use the account connection form for exchange credentials.'] },
      { title: '3. Service providers and sharing', paragraphs: ['The service uses Supabase for authentication and database services and Vercel for website hosting. Google sign-in is optional. Connected exchanges process requests under their own terms and privacy policies. Market-data services used by the signed-in dashboard may receive network information when your browser connects to them. Necessary data may also be disclosed to comply with lawful requirements or protect rights and security. These providers may process information outside your location under their own applicable safeguards and terms.'] },
      { title: '4. Account records and downloaded invoices', paragraphs: ['Account and billing information is retained in the database so that the service can function and records can be reviewed. Invoice documents are generated when requested; the application does not keep a separate stored PDF for each invoice. A PDF you download is a file on your own device and remains under your control.'] },
      { title: '5. Retention and requests', paragraphs: ['Information is kept for as long as needed for the stated service purposes, security, dispute handling, and applicable legal obligations. Some billing or transaction records may need to be retained after account closure. Contact support@profitpilot.in to request information, correction, deletion, withdrawal of consent where applicable, or to raise a privacy grievance. Identity verification may be required before acting on a request. Withdrawing information needed to operate a feature may prevent further use of that feature.'] },
      { title: '6. Cookies and browser storage', paragraphs: ['Authentication cookies maintain your session. Browser storage remembers your theme preference and helps propagate logout across tabs. See the Cookie Policy for more detail. Clearing authentication storage signs you out; clearing preference storage resets saved choices.'] },
      { title: '7. Security and changes', paragraphs: ['Access controls limit customer data to authorized users. No networked service can promise absolute security. Notify support promptly if you suspect unauthorized account access, and revoke compromised exchange credentials at the exchange. This notice may change as the service changes. The date above identifies the current version. Privacy requests are handled subject to applicable Indian data-protection requirements.'] },
    ],
  },
  'risk-disclosure': {
    title: 'Risk disclosure', description: 'Read this before connecting an account or using automated trading.', sections: [
      { title: '1. Loss of capital', paragraphs: ['Crypto derivatives are high-risk products. Prices can move rapidly and leverage can magnify losses. You can lose your trading capital, and your obligations depend on the exchange’s product and margin rules. Use only funds you can afford to lose and assess whether the products are appropriate for you.'] },
      { title: '2. Options, margin, and liquidation', paragraphs: ['Options exposure can change quickly. Selling options can create substantial losses, and margin requirements can increase during stressed markets. A position may be liquidated by the exchange independently of ProfitPilot’s controls. Available margin, a dashboard status, or a risk indicator is not a promise that an account is safe.'] },
      { title: '3. Execution and technology', paragraphs: ['Orders can be rejected, partially filled, delayed, or filled at prices different from those expected. Liquidity, spreads, slippage, fees, and exchange outages affect results. Networks, API limits, credentials, software faults, and unavailable or stale data can interrupt operation. Stop or close controls cannot guarantee execution at a specific price or time.'] },
      { title: '4. Automated operation', paragraphs: ['Automation follows configured behavior; it does not exercise your personal judgment or guarantee a result. You remain responsible for monitoring the account and understanding its controls. Pausing new entries is different from closing existing positions. Keep independent access to your exchange account and verify positions directly when the website or data is unavailable.'] },
      { title: '5. Performance, currency, and costs', paragraphs: ['Past results, illustrative charts, and simulated outcomes do not predict future results. Open P&L is an estimate until execution and fees settle. Exchange fees, taxes, funding or other product charges, and service fees can reduce returns. INR account values use Delta Exchange India’s fixed rate of ₹85 per USD, rather than a live foreign-exchange rate. Data timing and unsettled P&L may still cause differences from the exchange.'] },
      { title: '6. Third parties and regulation', paragraphs: ['Exchange custody, solvency, legal availability, and product rules are outside the website’s control. Laws, taxes, and exchange requirements may change. Confirm your eligibility and obligations independently. Where appropriate, obtain advice from a qualified professional who understands your situation.'] },
    ],
  },
  disclaimer: {
    title: 'Disclaimer', description: 'How to interpret the information shown on this website.', sections: [
      { title: 'Software and general information', paragraphs: ['ProfitPilot provides software and general product information. Website text, interface examples, charts, and support material do not constitute a personal recommendation to buy, sell, or hold an asset or a guarantee about a trading outcome. The website does not claim regulatory approval or investment-adviser status.'] },
      { title: 'Product demonstrations', paragraphs: ['Public demo balances, charts, positions, and statements are illustrative interface examples. They do not describe a real customer account, independently verified performance, or expected returns. Real account information is available only in the authenticated workspace. Do not interpret a product illustration as evidence of profitability.'] },
      { title: 'Accuracy and data timing', paragraphs: ['Data can be delayed, incomplete, or temporarily unavailable. Displayed balances and unrealized results should be checked against the exchange when making account decisions. INR displays use Delta Exchange India’s fixed rate of ₹85 per USD. Billing records and the connected exchange’s records govern their respective underlying amounts.'] },
      { title: 'Third-party names and links', paragraphs: ['Exchange and service-provider names identify integrations or linked services. Their inclusion does not imply endorsement, partnership, or regulatory authorization. Third-party sites have their own terms and privacy practices.'] },
      { title: 'Questions or corrections', paragraphs: ['If a display, invoice, or description appears incorrect, contact support@profitpilot.in with the relevant reference and a description of the issue. Never include passwords or API secrets. Nothing in this disclaimer limits rights that cannot be limited under applicable law.'] },
    ],
  },
  'refund-policy': {
    title: 'Billing & refunds', description: 'How to review charges, raise a billing issue, or stop using the service.', sections: [
      { title: 'Performance-based billing', paragraphs: ['The published model charges 30% of eligible net new realized profit after applicable loss carryover. Statements are based on completed calendar-month records. A No Fee statement does not require payment. A displayed product example is not an invoice or an amount you owe. Review your own invoice before making a payment.'] },
      { title: 'Incorrect or duplicate charges', paragraphs: ['If you believe a charge is duplicated or incorrect, contact support@profitpilot.in with your invoice reference, account email, and an explanation. Include a payment reference if you have already paid; do not send full payment credentials. The record and calculation will be reviewed. Confirmed billing errors will be addressed through a correction, credit, or refund as appropriate and subject to applicable law.'] },
      { title: 'Service fees and trading losses', paragraphs: ['Trading losses, exchange fees, and taxes are separate from ProfitPilot service charges. A refund of a service charge is not insurance against market losses and does not reverse a trade at the exchange. Any rights that apply under law remain unaffected.'] },
      { title: 'Stopping or closing your account', paragraphs: ['You can pause new entries using the dashboard and revoke the exchange API key directly at the exchange. Existing positions are not automatically closed by pausing or revoking access. Verify and manage them at the exchange. Contact support to request website account closure and resolution of outstanding billing matters.'] },
      { title: 'Review and communication', paragraphs: ['Support may request information needed to validate a dispute or locate a payment. Keep your invoice and payment reference until the issue is resolved. Refund method and timing depend on the payment method and the outcome of the review; no automatic refund period is represented on this website.'] },
    ],
  },
  cookies: {
    title: 'Cookie policy', description: 'The browser storage used to make sign-in and preferences work.', sections: [
      { title: 'Authentication cookies', paragraphs: ['Supabase authentication cookies are used to recognize a signed-in session and refresh it when appropriate. Session information may be split across several cookies. These cookies are required to use the protected account area. Logging out clears the local session; blocking essential authentication cookies may prevent sign-in from working.'] },
      { title: 'Preferences and logout coordination', paragraphs: ['Local browser storage remembers your light or dark theme selection. A logout marker helps other open tabs return to the sign-in page when you log out. These records are used for interface behavior rather than to show advertising.'] },
      { title: 'Third-party services', paragraphs: ['If you choose Google sign-in or follow an external support or exchange link, that provider may use its own cookies and storage under its own policy. Hosting and security infrastructure may also use storage needed to deliver and protect the service.'] },
      { title: 'Your choices', paragraphs: ['You can clear or block cookies and local storage through your browser. This may sign you out and reset your saved theme. The public product preview does not require a trading connection. Contact support@profitpilot.in with questions about browser storage.'] },
    ],
  },
};

export const pageDetails: Record<string, { title: string; description: string; category: string }> = {
  product: { title: 'One workspace. The full picture.', description: 'A connected view of your account, trading activity, and records. Designed to be useful at a glance and clear when you look closer.', category: 'THE PLATFORM' },
  demo: { title: 'Take a look around.', description: 'Explore an interactive product preview. Switch between account views, activity, and invoices. All figures below are illustrative; no account or trading connection is required.', category: 'INTERACTIVE DEMO' },
  performance: { title: 'Results with context.', description: 'Understand your own trading record through realized results, closed trades, and clear account reporting.', category: 'PERFORMANCE & REPORTING' },
  pricing: { title: 'A fee tied to net new profit.', description: 'Performance-based pricing, with loss carryover and a statement you can review.', category: 'CLEAR, CONSIDERED PRICING' },
  security: { title: 'Your account. Your control.', description: 'A separate trading workspace, connected to the exchange account you own.', category: 'ACCOUNT & SECURITY' },
  resources: { title: 'A useful place to start.', description: 'Get to know the platform, find answers, and understand the records and controls in your account.', category: 'RESOURCES' },
  help: { title: 'How can we help?', description: 'Practical answers for your account, dashboard, and invoices.', category: 'HELP CENTER' },
  about: { title: 'Built for a clearer perspective.', description: 'ProfitPilot brings the account side of automated trading into one focused workspace.', category: 'ABOUT PROFITPILOT' },
  contact: { title: 'Let’s talk.', description: 'Questions about the product, an account, or a billing record? Start here.', category: 'CONTACT' },
};
