import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Activity, ArrowRight, ArrowUpRight, BarChart3, Check, CreditCard, KeyRound, Mail, Monitor, ShieldCheck, Smartphone } from 'lucide-react';
import { SiteShell } from '@/components/marketing/site-shell';
import { ProductPreview } from '@/components/marketing/product-preview';
import { pageDetails, policies } from '@/lib/site-content';

export const dynamicParams = false;
export function generateStaticParams() { return [...Object.keys(pageDetails), ...Object.keys(policies)].map(slug => ({ slug })); }
export function generateMetadata({ params }: { params: { slug: string } }): Metadata {
  const page = pageDetails[params.slug] || policies[params.slug];
  return page ? { title: `${page.title} | ProfitPilot`, description: page.description } : {};
}
function Callout({ title = 'See the workspace for yourself.', text = 'Explore the demo, then open your own account when you are ready.', href = '/demo', label = 'Explore demo' }: { title?: string; text?: string; href?: string; label?: string }) {
  return <div className="page-callout"><div><h2>{title}</h2><p>{text}</p></div><Link href={href} className="site-button primary">{label}<ArrowUpRight size={16}/></Link></div>;
}

function PageContent({ slug }: { slug: string }) {
  if (slug === 'demo') return <><ProductPreview expanded /><Callout title="Make it your workspace." text="Sign in to view your own connected account. The preview above is illustrative." href="/login" label="Open your account" /></>;
  if (slug === 'product') return <><ProductPreview expanded /><div className="page-grid" style={{ marginTop: 36 }}>{[{ icon:Monitor,title:'An account overview that reads clearly',text:'See account balances, available margin, open positions, and recent results together. Data freshness is visible so you know when a figure needs checking.' },{icon:Smartphone,title:'Built for desktop and mobile',text:'A compact phone layout keeps navigation within reach, while the desktop workspace provides room to inspect your account in detail.'},{icon:CreditCard,title:'Records that are easy to revisit',text:'Review closed trades and monthly statements. Preview an invoice or download it as a PDF when you need it.'}].map(item=><article className="content-card" key={item.title}><item.icon size={24}/><h2>{item.title}</h2><p>{item.text}</p></article>)}</div><Callout /></>;
  if (slug === 'performance') return <><div className="page-grid">{[{icon:BarChart3,title:'Realized results',text:'A view of recorded closed-trade results. Realized trading P&L is shown separately from account balance and open-position estimates.'},{icon:Activity,title:'A traceable history',text:'Inspect individual closed trades and their recorded results. Incomplete or unreconciled records should be resolved before relying on an aggregate.'},{icon:ShieldCheck,title:'Your data stays in your workspace',text:'Customer balances and trading records are not published on this website. Sign in to see your own performance. Public demo charts are illustrative.'}].map(item=><article className="content-card" key={item.title}><item.icon size={24}/><h2>{item.title}</h2><p>{item.text}</p></article>)}</div><Callout title="Review your own record." text="Open your dashboard for account-specific results and closed trades." href="/dashboard" label="View dashboard" /><p className="text-sm text-[var(--grey)]">Past performance and simulated outcomes do not predict future results. Read our <Link className="underline" href="/risk-disclosure">risk disclosure</Link>.</p></>;
  if (slug === 'pricing') return <><div className="pricing-layout"><section className="pricing-main"><p className="eyebrow">PERFORMANCE-BASED</p><div className="pricing-value">30<span className="text-4xl">%</span></div><p>of eligible net new realized profit,<br/>after applicable carried-forward losses.</p><ul>{['Loss carryover before new performance fees','Calendar-month billing records','On-demand invoice preview and PDF download','USD billing · INR display at ₹85 per USD'].map(text=><li key={text}><Check size={16}/>{text}</li>)}</ul><Link className="site-button primary" href="/login">Open your account <ArrowRight size={16}/></Link></section><section className="pricing-example"><span className="micro-label">ILLUSTRATIVE BILLING EXAMPLE · USD</span><h2 className="mt-4">The calculation, in plain view.</h2><p>This example explains the fee. It is not a forecast or a promised monthly return.</p><dl><div><dt>Realized trading profit</dt><dd>$1,000.00</dd></div><div><dt>Previous losses carried forward</dt><dd>−$200.00</dd></div><div><dt>Net billable profit</dt><dd>$800.00</dd></div><div><dt>Performance fee · 30%</dt><dd>$240.00</dd></div></dl><p>No eligible net new profit means no performance fee for that period. Exchange fees, taxes, and other exchange charges are separate from the service fee.</p><Link className="text-link" href="/refund-policy">Billing questions & refunds <ArrowUpRight size={15}/></Link></section></div><Callout title="Questions about an invoice?" text="Send the invoice reference to support so the record can be reviewed." href="/contact" label="Contact support" /></>;
  if (slug === 'security') return <><div className="page-grid">{[{icon:KeyRound,title:'A connection you manage',text:'Use an exchange API key with the permissions needed for trading and no withdrawal permission. You can revoke the key directly at the exchange.'},{icon:ShieldCheck,title:'Protected account access',text:'Your workspace requires sign-in, and account records are restricted to authorized access. Logging out ends the local session and clears protected views across tabs.'},{icon:Activity,title:'Visibility into account status',text:'Data freshness and trading status are shown in the dashboard. Keep independent access to your exchange and check it directly if website data is unavailable.'}].map(item=><article className="content-card" key={item.title}><item.icon size={24}/><h2>{item.title}</h2><p>{item.text}</p></article>)}</div><Callout title="Understand the boundaries." text="Security controls do not eliminate market, execution, or technology risk." href="/risk-disclosure" label="Read risk disclosure" /><div className="content-card"><h2>Something doesn’t look right?</h2><p>Contact support if you suspect unauthorized access. Revoke compromised keys at the exchange and do not send passwords or API secrets in a support message.</p><Link href="/contact">Contact support <ArrowUpRight size={15}/></Link></div></>;
  if (slug === 'resources') return <>{[['01','Get to know the workspace','Account views, mobile access, and the records available to you.','/product'],['02','Help center','Answers about sign-in, currency display, invoices, and account controls.','/help'],['03','Understand your billing','Performance fees, carried-forward losses, and invoice review.','/pricing'],['04','Account security','Your exchange connection, sign-in, and account access.','/security'],['05','Understand the risks','The risks associated with crypto derivatives and automated operation.','/risk-disclosure']].map(([n,title,text,href])=><Link href={href} className="resource-row" key={href}><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div><ArrowUpRight size={22}/></Link>)}</>;
  if (slug === 'help') return <>{[
    ['How do I access my workspace?', 'Use Log in to sign in with your existing account. You can also create an account on the sign-in page. The public demo is available without signing in and contains sample data only.'],
    ['How are INR figures calculated?', 'INR figures equal the USD amount multiplied by 85, matching Delta Exchange India’s fixed rate. For example, $100 displays as ₹8,500. This is not a live foreign-exchange rate. Stored billing records and invoice totals remain in USD. Data timing and unsettled P&L can still cause differences.'],
    ['How do I download an invoice?', 'Open Invoices in your dashboard, choose the invoice reference, then select Download PDF. The document is generated from the stored billing record when requested.'],
    ['Why does a value say Unavailable?', 'Some account figures require recent telemetry or complete records. Unavailable means a figure cannot be confirmed, rather than a balance of zero. Check your exchange directly when necessary.'],
    ['Does pausing close existing positions?', 'No. Pausing new entries and requesting a position close are separate controls. A close request depends on execution at the exchange. Always confirm final position status directly.'],
    ['Why are there two statements for the same period?', 'Check the invoice reference to distinguish records. If you believe a statement or charge is duplicated, contact support before making a payment. Do not assume two records mean two amounts are owed.'],
    ['How do I close my account?', 'First review your open positions and connection at the exchange. Contact support for website account closure and outstanding billing questions. Revoking API access does not automatically close exchange positions.'],
  ].map(([q,a])=><details className="help-item" key={q}><summary>{q}</summary><p>{a}</p></details>)}<Callout title="Still need a hand?" text="Contact support with your account or invoice reference. Leave out passwords and API secrets." href="/contact" label="Contact support" /></>;
  if (slug === 'about') return <><div className="page-grid">{[{title:'Clarity over clutter',text:'A trading workspace should help you find what matters: the account, its positions, and the record behind the numbers. That is the focus of ProfitPilot.'},{title:'Continuity across your day',text:'The desktop and mobile experiences share the same account context, so you can move between a deeper review and a quick check-in.'},{title:'A record you can revisit',text:'Trading activity and billing should be understandable after the moment has passed. Clear statements and accessible history are part of the product.'}].map(item=><article className="content-card" key={item.title}><h2>{item.title}</h2><p>{item.text}</p></article>)}</div><Callout title="Get to know the product." /></>;
  if (slug === 'contact') return <><div className="page-grid"><article className="content-card"><Mail size={25}/><h2>Account & product support</h2><p>For product questions, connection help, billing review, or account requests.</p><a href="mailto:support@profitpilot.in">support@profitpilot.in <ArrowUpRight size={15}/></a></article><article className="content-card"><CreditCard size={25}/><h2>Billing questions</h2><p>Include your account email and invoice reference so the right record can be found. Do not share full payment credentials.</p><Link href="/refund-policy">Billing & refunds <ArrowUpRight size={15}/></Link></article><article className="content-card"><ShieldCheck size={25}/><h2>Privacy & security</h2><p>Use the same support address for data requests or suspected unauthorized access. Never send API secrets or passwords.</p><Link href="/privacy">Privacy information <ArrowUpRight size={15}/></Link></article></div><div className="page-callout"><div><h2>For urgent exchange account issues</h2><p>Use your exchange directly to verify positions, manage access, or review an order. Email support is not an emergency order-execution channel.</p></div></div></>;
  return null;
}

export default function PublicPage({ params }: { params: { slug: string } }) {
  const { slug } = params;
  const policy = policies[slug]; const details = pageDetails[slug];
  if (!policy && !details) notFound();
  const info = policy || details;
  return <SiteShell><div className="site-container"><header className="page-hero"><p className="eyebrow">{policy ? 'POLICIES & DISCLOSURES' : details.category}</p><h1>{info.title}</h1><p>{info.description}</p></header>
    {policy ? <div className="policy-layout"><nav className="policy-nav" aria-label="Legal pages"><h2>Policies & disclosures</h2>{Object.entries(policies).map(([key,p])=><Link key={key} href={`/${key}`} aria-current={key === slug ? 'page' : undefined}>{p.title}</Link>)}</nav><article className="policy-body"><p className="policy-meta">Last updated: 8 September 2026 · India</p>{policy.sections.map((section,i)=><section key={section.title} id={`section-${i+1}`}><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.bullets && <ul>{section.bullets.map(p=><li key={p}>{p}</li>)}</ul>}</section>)}<div className="policy-contact"><h2>Questions about this policy?</h2><p>Email <a href="mailto:support@profitpilot.in">support@profitpilot.in</a> or visit our <Link href="/contact">contact page</Link>.</p></div></article></div> : <div className="page-content"><PageContent slug={slug}/></div>}
  </div></SiteShell>;
}
